/* tslint:disable */
/* eslint-disable */
/**
 * ZG Backend API
 * Backend app for ZmeyGorynych project. Written for fun :)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

